#+TITLE: Current Buffer
#+SUBTITLE: Utilities for operating on the current buffer in Emacs
#+AUTHOR: Joseph M LaFreniere (lafrenierejm)

/Current Buffer/ is an Emacs library providing utilities for operating on the current buffer.


* Usage

As noted in the package commentary, keybindings are not added by this package.
This is a deliberate decision to avoid the possibility of conflicting with any user's existing keybindings.
Instead, users are encouraged to add bindings themselves for interactive use.
One example using [[https://github.com/jwiegley/use-package][use-package]], [[https://github.com/raxod502/straight.el][straight]], [[https://github.com/noctuid/general.el][general]], and [[https://github.com/emacs-evil/evil][evil]] is
#+begin_src emacs-lisp
(use-package current-buffer
  :straight (:host github
             :repo "lafrenierejm/current-buffer.el")

  :general
  ("C-d" #'current-buffer-dired)
  ("C-x C-S-d" #'current-buffer-delete)
  ("C-x C-c" #'current-buffer-copy)
  ("C-x C-k" #'current-buffer-kill)
  ("C-x C-r" #'current-buffer-rename)
  ("C-x y" #'current-buffer-yank-name)
  ("C-x C-y" #'current-buffer-yank-path)
  (:states '(normal)
   "g r" #'current-buffer-revert))
#+end_src

* License

Copyright © 2022 Joseph M LaFreniere.

This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.

The full license text is available at [[file:LICENSE][LICENSE]].
